# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: People
    url: 'people/'
    weight: 20
  - name: Research
    url: 'research/'
    weight: 25
  - name: Publications
    url: 'publications/'
    weight: 30
  - name: Software
    url: 'software/'
    weight: 35
  - name: Teaching
    identifier: teaching
    weight: 40
  - name: Calculus
    url: 'teaching/calculus/'
    parent: teaching
    weight: 1
  - name: Differential Equations
    url: 'teaching/differential-equations/'
    parent: teaching
    weight: 2
  - name: Stochastic Processes
    url: 'teaching/stochastic-processes/'
    parent: teaching
    weight: 3
  - name: Data Visualization
    url: 'teaching/data-visualization/'
    parent: teaching
    weight: 4
  - name: Mathematical Biology
    url: 'teaching/mathematical-biology/'
    parent: teaching
    weight: 5
  - name: Teaching Pedagogy
    url: 'teaching/teaching-pedagogy/'
    parent: teaching
    weight: 6
  - name: Talks
    url: 'talks/'
    weight: 50
  - name: Contact
    url: 'contact/'
    weight: 70
  # - name: CV
  #   url: 'cv/'
  #   weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/thomas_bury_cv.pdf
#    weight: 90
